version: 0.5.0
profiles:
  zero:
    emoji_allowlist: []
    file_ignore_list: []
    directory_ignore_list: [.git, vendor, dist, bin, node_modules, examples, .cursor, docs_backup_20250903_141556]
    description: "Strict zero-tolerance profile - no emojis anywhere"

  ci-lint:
    emoji_allowlist:
      - "✅"
      - "❌"
      - "⚠️"
      - "✨"
      - ":("
      - ":/"
    file_ignore_list:
      - '**/*_test.go'
      - '**/test/**/*'
      - '**/testdata/**/*'
      - '**/fixtures/**/*'
      - README.md
      - CHANGELOG.md
      - .github/**/*
      - scripts/**/*
      - vendor/**/*
      - dist/**/*
      - bin/**/*
      - 'examples/**/*'
      - 'PRECOMMIT_REFACTOR_SUMMARY.md'
    directory_ignore_list: [.git, vendor, dist, bin, node_modules, examples, .cursor, docs_backup_20250903_141556]
    description: "CI-friendly profile with some allowed emojis"
