version: 2

run:
  timeout: 5m
  tests: true
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$" 
    - ".*_gen\\.go$"
  skip-dirs:
    - vendor
    - test/fixtures
    - .git

output:
  color: always
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - gosec
    - bodyclose
    - noctx

linters-settings:
  gocyclo:
    min-complexity: 25  # Temporarily relaxed for CI setup
  gosec:
    severity: medium
    confidence: medium
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - hugeParam  # Temporarily disabled
      - rangeValCopy  # Temporarily disabled
      - singleCaseSwitch  # Temporarily disabled

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocritic
    - path: cmd/antimoji/main\.go
      linters:
        - gochecknoinits
  max-issues-per-linter: 0
  max-same-issues: 0