# golangci-lint configuration
# Antimoji integration handled via pre-commit hooks and CI steps

version: "2"

run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Report suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - misspell      # Finds commonly misspelled English words
  disable:
    - unused        # Temporarily disabled - functions may be used in future
    - gosec         # Temporarily disabled - test files use 0644 permissions

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
