# golangci-lint configuration for Antimoji
# For full documentation, see: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Report suspicious constructs  
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Find unused code
    - misspell      # Finds commonly misspelled English words

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
