# Pre-commit hooks for Antimoji
# This file defines hooks that other projects can use
# See https://pre-commit.com/hooks.html for hook configuration

- id: antimoji-lint
  name: Antimoji Emoji Linter
  description: Check source code files for unwanted emojis
  entry: antimoji scan --threshold=0 --ignore-allowlist --quiet
  language: golang
  files: \.(go|js|ts|jsx|tsx|py|rb|java|c|cpp|h|hpp|rs|php|swift|kt|scala)$
  exclude: |
    (?x)^(
      .*_test\.|
      .*/test/.*|
      .*/tests/.*|
      .*/testdata/.*|
      .*/fixtures/.*|
      .*/mocks/.*|
      vendor/.*|
      node_modules/.*|
      dist/.*|
      bin/.*
    )$
  pass_filenames: true
  require_serial: false

- id: antimoji-lint-config
  name: Antimoji Config-based Linter
  description: Check files using custom antimoji configuration
  entry: antimoji scan --config=.antimoji.yaml --threshold=0 --quiet
  language: golang
  files: \.(go|js|ts|jsx|tsx|py|rb|java|c|cpp|h|hpp|rs|php|swift|kt|scala)$
  exclude: |
    (?x)^(
      .*_test\.|
      .*/test/.*|
      .*/tests/.*|
      .*/testdata/.*|
      .*/fixtures/.*|
      .*/mocks/.*|
      vendor/.*|
      node_modules/.*|
      dist/.*|
      bin/.*
    )$
  pass_filenames: true
  require_serial: false

- id: antimoji-docs
  name: Antimoji Documentation Checker
  description: Check documentation for excessive emoji usage
  entry: antimoji scan --threshold=5 --quiet
  language: golang
  files: \.(md|rst|txt)$
  exclude: |
    (?x)^(
      vendor/.*|
      node_modules/.*|
      dist/.*|
      bin/.*|
      \.git/.*
    )$
  pass_filenames: true
  require_serial: false

- id: antimoji-clean
  name: Antimoji Emoji Cleaner
  description: Remove emojis from source code files (with backup)
  entry: antimoji clean --in-place --backup --quiet
  language: golang
  files: \.(go|js|ts|jsx|tsx|py|rb|java|c|cpp|h|hpp|rs|php|swift|kt|scala)$
  exclude: |
    (?x)^(
      .*_test\.|
      .*/test/.*|
      .*/tests/.*|
      .*/testdata/.*|
      .*/fixtures/.*|
      .*/mocks/.*|
      vendor/.*|
      node_modules/.*|
      dist/.*|
      bin/.*
    )$
  pass_filenames: true
  require_serial: false

- id: antimoji-generate-config
  name: Antimoji Config Generator
  description: Generate antimoji configuration based on current project
  entry: antimoji generate --type=ci-lint --output=.antimoji.yaml
  language: golang
  files: \.antimoji\.yaml$
  pass_filenames: false
  require_serial: true
  always_run: true